<%@ Page Title="" Language="C#" MasterPageFile="~/Master.master" AutoEventWireup="true" CodeFile="Sql_I.aspx.cs" Inherits="languages_php_PHP_I" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style6 {
            font-size: x-large;
        }
        .auto-style21 {
            font-size: medium;
            height: 120px;
            text-align: center;
        }
        .auto-style30 {
            text-align: left;
        }
        .auto-style31 {
            width: 60%;
            padding: 40px;
        }
        .auto-style32 {
            width: 40%;
            padding: 40px;
        }
        .auto-style33 {
            font-weight: normal;
        }
        .auto-style50 {
            border-radius:10px;
            box-shadow:3px 3px 3px 3px #999;
            width: 100%;
        }
        .auto-style52 {
            font-size: xx-large;
        }
        .auto-style53 {
            font-size: 36pt;
        }
        .auto-style54 {
            font-size: 24pt;
        }
        .auto-style55 {
            font-size: 17pt;
        }
        .auto-style56 {
            text-align: right;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div>
        <table class="auto-style50" style="background-color:#66CCFF">
            <tr">
                <td class="auto-style31" style="background-color: #66CCFF">
                    <h1 class="auto-style33">&nbsp;</h1>
                    <strong><span class="auto-style53">SQL</span><span class="auto-style52"><br />
                    </span></strong><span class="auto-style54">(MySQL)</span><p><span class="auto-style52">공식 사이트 :
                        </span>
                        <asp:LinkButton ID="LinkButton4" runat="server" PostBackUrl="https://www.mysql.com/" CssClass="auto-style52">https://www.mysql.com/</asp:LinkButton>
                    </p>
                </td>
                <td class="auto-style32" style="background-color: #66CCFF">
        <strong>
                <asp:Image ID="Image2" runat="server" Height="226px" ImageUrl="~/objects/images/SQL_icon.png" Width="223px" />
                </strong></td>
            </tr>
        </table>
    </div>
    <h1 class="auto-style30">
        소개</h1>
    
    <p class="auto-style6">
        1995년에 발표된 오픈 소스 DBMS(DataBase Management System)이다.</p>
    <p class="auto-style6">
        &nbsp;제작사는 MySQL AB이지만 이 회사는 썬 마이크로시스템즈에게 10억 달러에 인수되었다.</p>
    <p class="auto-style6">
        이후 2010년 오라클이 썬을 72억 달러에 인수하면서 오라클 소속이 되었다.</p>
    <p class="auto-style6">
        점유율은 매우 높으며, 설치형 블로그나 게시판 등등 상당수의 CMS(컨텐츠 관리 시스템)가 MySQL을 지원한다.</p>
    <p class="auto-style6">
        &nbsp;</p>
    <h1>
        특징</h1>
    <p class="auto-style6">
        -
        공통적으로 대문자는 키워드, 소문자는 이름이나 값 등 변수를 의미하고, 주로 사용되는 WHERE 옵션은 중괄호로 표기한다.</p>
    <p class="auto-style6">
        &nbsp;- SQL은 대소문자를 구분하지 않으므로 SELECT와 select는 같은 것이다.</p>
    <p class="auto-style6">
        - 따옴표로 인용된 &#39;값&#39;은 대소문자를 구분한다. 또한 대부분의 DBMS는 세미콜론(;)을 입력하지 않으면 명령어를 계속 입력하고 있다고 간주한다.</p>
    <h1>
        간결한 문법</h1>
    <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: bold !important; font-style: normal; min-height: auto !important; color: rgb(0, 102, 153) !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;INSERT</code><span class="auto-style55" style="color: rgb(102, 102, 102); font-family: Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 250, 252); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
    </span>
    <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: bold !important; font-style: normal; min-height: auto !important; color: rgb(0, 102, 153) !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    INTO</code><span class="auto-style55" style="color: rgb(102, 102, 102); font-family: Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 250, 252); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> </span>
    <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: black !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    table_name </code>
    <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: bold !important; font-style: normal; min-height: auto !important; color: rgb(0, 102, 153) !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    VALUES</code><span class="auto-style55" style="color: rgb(102, 102, 102); font-family: Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 250, 252); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> </span>
    <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: black !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
    (value1, value2, value3,...)</code><p>
        <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: bold !important; font-style: normal; min-height: auto !important; color: rgb(0, 102, 153) !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">&nbsp;INSERT</code><span class="auto-style55" style="color: rgb(102, 102, 102); font-family: Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 250, 252); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
        </span>
        <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: bold !important; font-style: normal; min-height: auto !important; color: rgb(0, 102, 153) !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        INTO</code><span class="auto-style55" style="color: rgb(102, 102, 102); font-family: Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 250, 252); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> </span>
        <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: black !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        `student` </code>
        <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: bold !important; font-style: normal; min-height: auto !important; color: rgb(0, 102, 153) !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        VALUES</code><span class="auto-style55" style="color: rgb(102, 102, 102); font-family: Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(244, 250, 252); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> </span>
        <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: black !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        (</code><code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: blue !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">&#39;1&#39;</code><code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: black !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">,
        </code>
        <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: blue !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        &#39;KIM&#39;</code><code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: black !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">,
        </code>&#39;<code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: blue !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">남자&#39;</code><code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: black !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">,
        </code>
        <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: blue !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        &#39;김해&#39;</code><code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: black !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">,
        </code>
        <code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: blue !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        &#39;2018-12-5&#39;</code><code class="auto-style55" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; color: black !important; font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">);</code></p>
    <p>
        &nbsp;</p>
    <p class="auto-style56">
        출처 : https://www.opentutorials.org</p>
<p class="auto-style21">
        <strong>
        <asp:Button ID="Button1" runat="server" BackColor="Purple" CssClass="auto-style6" ForeColor="White" Height="87px" OnClick="Button1_Click" Text="Back" Width="196px" />
        </strong></p>
</asp:Content>

