<%@ Page Title="" Language="C#" MasterPageFile="~/Master.master" AutoEventWireup="true" CodeFile="Sql_III.aspx.cs" Inherits="languages_php_PHP_II" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            text-align: left;
        }
        .auto-style2 {
            text-align: left;
            font-size: x-large;
        }
        .auto-style3 {
            font-size: x-large;
        }
        .auto-style21 {
            font-size: medium;
            height: 120px;
            text-align: center;
        }
        .auto-style22 {
            text-align: center;
            width: 200px;
            font-size: x-large;
        }
        .auto-style23 {
            font-size: 17pt;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p class="auto-style1">
        <br class="auto-style3" />
        <span class="auto-style23" style="color: rgb(55, 58, 60); font-family: &quot;open sans&quot;, arial, &quot;apple sd gothic neo&quot;, &quot;noto sans cjk kr&quot;, 본고딕, &quot;kopubdotum medium&quot;, 나눔바른고딕, 나눔고딕, nanumgothic, 맑은고딕, &quot;malgun gothic&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">DELETE : 데이터를 삭제하는 구문.</span></p>
    <p class="auto-style2">
        <span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">DELETE</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
        </span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">FROM</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
        </span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">table</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> 
        {</span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">WHERE</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> 
        조건};</span></p>
    <p class="auto-style2">
        &nbsp;</p>
    <p class="auto-style2">
        <span class="auto-style23" style="color: rgb(55, 58, 60); font-family: &quot;open sans&quot;, arial, &quot;apple sd gothic neo&quot;, &quot;noto sans cjk kr&quot;, 본고딕, &quot;kopubdotum medium&quot;, 나눔바른고딕, 나눔고딕, nanumgothic, 맑은고딕, &quot;malgun gothic&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: left; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">SELECT : 데이터를 읽어오는 구문. 현업에서 사용하다 보면 가장 복잡하고 고려할 사항이 많은, 중요하고 어려운 구문이다.</span></p>
    <p class="auto-style2">
        <span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">SELECT</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> 
        field1, field2, ... </span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">FROM</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
        </span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">table</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> 
        {</span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">WHERE</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> 
        조건};</span></p>
    <p class="auto-style2">
        <span class="auto-style23" style="color: rgb(55, 58, 60); font-family: &quot;open sans&quot;, arial, &quot;apple sd gothic neo&quot;, &quot;noto sans cjk kr&quot;, 본고딕, &quot;kopubdotum medium&quot;, 나눔바른고딕, 나눔고딕, nanumgothic, 맑은고딕, &quot;malgun gothic&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(238, 238, 238); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">ex) SELECT * FROM document WHERE author=&#39;KIM&#39;;</span></p>
    <p class="auto-style2">
        <span class="auto-style23" style="color: rgb(55, 58, 60); font-family: &quot;open sans&quot;, arial, &quot;apple sd gothic neo&quot;, &quot;noto sans cjk kr&quot;, 본고딕, &quot;kopubdotum medium&quot;, 나눔바른고딕, 나눔고딕, nanumgothic, 맑은고딕, &quot;malgun gothic&quot;, sans-serif; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(작성자가 &#39;KIM&#39;인 모든 문서의 모든 항목를 가져오는 구문)</span></p>
    <p class="auto-style2">
        &nbsp;</p>
<p class="auto-style21">
        <strong>
        <asp:Button ID="Button1" runat="server" BackColor="Purple" CssClass="auto-style22" ForeColor="White" Height="87px" OnClick="Button1_Click" Text="Back" Width="196px" />
        </strong></p>
</asp:Content>

