<%@ Page Title="" Language="C#" MasterPageFile="~/Master.master" AutoEventWireup="true" CodeFile="Sql_II.aspx.cs" Inherits="languages_php_PHP_II" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style1 {
            text-align: left;
        }
        .auto-style2 {
            text-align: left;
            font-size: x-large;
        }
        .auto-style3 {
            font-size: x-large;
        }
        .auto-style21 {
            font-size: medium;
            height: 120px;
            text-align: center;
        }
        .auto-style22 {
            text-align: center;
            width: 200px;
            font-size: x-large;
        }
        .auto-style23 {
            font-size: 17pt;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <p class="auto-style1" >
        <br class="auto-style3" />
        </p>
    <strong><span class="auto-style23">INSERT</span></strong><span class="auto-style23"> : 데이터를 입력하는 구문이다.</span><br class="auto-style23" />
    <br class="auto-style23" />
    <span class="auto-style23">table에 field1=value1, field2=value2, ...와 같은 속성값을 가지는 항목을 새로 생성하여 삽입한다. 만약 테이블에 입력될 값이 문자라면 반드시&nbsp;&#39;&#39;&nbsp;으로 문자열 (String)임을 표시해주어야한다.</span><br class="auto-style23" />
    <br class="auto-style23" />
    <span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">INSERT</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
    </span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">INTO</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
    </span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">table</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">(field1, 
    field2, ...) </span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">VALUES</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> 
    (value1, value2, ...);</span><br class="auto-style23" />
    <br class="auto-style23" />
    <br class="auto-style23" />
    <br class="auto-style23" />
    <strong><span class="auto-style23">UPDATE</span></strong><span class="auto-style23"> : 데이터를 수정하는 구문이다.</span><br class="auto-style23" />
    <br class="auto-style23" />
    <span class="auto-style23">table의 field1에 value1, field2에 value2, ... 로 변경한다.
    <br />
    </span>
    <br class="auto-style23" />
    <span class="auto-style23">WHERE 절이 없을 경우 테이블의 모든 항목이 바뀌므로, 대개 WHERE절과 함께 사용하여 범위를 한정해 준다. </span>
    <p class="auto-style2" >
        <span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">UPDATE</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
        </span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">table</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">
        </span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">SET</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> 
        field1</span><span class="cs-default-sql-normal" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"></span><span class="auto-style23" style="color: rgb(0, 153, 204); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">=</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">value1, 
        field2</span><span class="cs-default-sql-normal" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-size: 12px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;"></span><span class="auto-style23" style="color: rgb(0, 153, 204); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">=</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;">value2, 
        {</span><span class="auto-style23" style="color: rgb(255, 51, 153); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial;">WHERE</span><span class="auto-style23" style="color: rgb(1, 1, 1); font-family: Consolas, &quot;liberation mono&quot;, Menlo, Courier, monospace; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: pre; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-style: initial; text-decoration-color: initial; display: inline !important; float: none;"> 
        조건};</span></p>
    <p class="auto-style21">
        <strong>
        <asp:Button ID="Button1" runat="server" BackColor="Purple" CssClass="auto-style22" ForeColor="White" Height="87px" OnClick="Button1_Click" Text="Back" Width="196px" />
        </strong></p>
</asp:Content>

