<%@ Page Title="" Language="C#" MasterPageFile="~/Master.master" AutoEventWireup="true" CodeFile="Sql_I.aspx.cs" Inherits="languages_php_PHP_I" %>

<asp:Content ID="Content1" ContentPlaceHolderID="head" Runat="Server">
    <style type="text/css">
        .auto-style6 {
            font-size: x-large;
        }
        .auto-style21 {
            font-size: medium;
            height: 120px;
            text-align: center;
        }
        .auto-style30 {
            text-align: left;
        }
        .auto-style31 {
            width: 60%;
            padding: 40px;
        }
        .auto-style32 {
            width: 40%;
            padding: 40px;
        }
        .auto-style33 {
            font-weight: normal;
        }
        .auto-style50 {
            border-radius:10px;
            box-shadow:3px 3px 3px 3px #999;
            width: 100%;
        }
        .auto-style51 {
            font-size: medium;
            height: 120px;
            text-align: right;
        }
        .auto-style52 {
            font-size: 20pt;
        }
    </style>
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" Runat="Server">
    <div>
        <table class="auto-style50" style="background-color:#66CCFF">
            <tr">
                <td class="auto-style31" style="background-color: #66CCFF">
                    <h1 class="auto-style33"><strong>PHP</strong></h1>
                    <p class="auto-style52">최초 개발자 : Rasmus Lerdorf</p>
                    <p class="auto-style52">운영 및 개발자 : The PHP Group</p>
                    <p><span class="auto-style52">공식 사이트 :
                        </span>
                        <asp:LinkButton ID="LinkButton4" runat="server" PostBackUrl="http://www.php.net" CssClass="auto-style52">http://www.php.net</asp:LinkButton>
                    </p>
                </td>
                <td class="auto-style32" style="background-color: #66CCFF">
        <strong>
                <asp:Image ID="Image2" runat="server" Height="176px" ImageUrl="~/objects/images/SQL_icon.png" Width="174px" />
                </strong></td>
            </tr>
        </table>
    </div>
    <h1 class="auto-style30">
        소개</h1>
    
    <p class="auto-style6">
        웹 서버에서 사용되는 대표적인 스크립트 언어이며,
        PHP는 1995년 Rasmus Lerdorf 프로그래머가 처음 고안하였다.</p>
    <p class="auto-style6">
        웹 개발 시 서버의 기능을 활용하기 위해 별도의 실행 파일을 만들 필요없이 PHP로 작성된 문서를 HTML 문서 안에 삽입하거나 별도의 문서로 만든다. 일반적으로 약어 PHP로 사용한다.
    </p>
    <p class="auto-style6">
        웹 서비스를 개발하는 경우 HTML과 CSS, 자바스크립트만으로도 가능하지만, 서버 내에서 실행되어야 하는 서버 관련 기능은 구현하기가 어렵다. 
    </p>
    <p class="auto-style6">
        예를 들어 서버와 클라이언트 간의 세션 관리, 사용자가 요청하는 정보를 데이터베이스에서 추출 및 전달하는 등의 기능은 구현하는 데 한계가 있다. PHP는 이러한 한계를 극복하기 위해 개발되었다.</p>
    <h1>
        특징</h1>
    <p class="auto-style6">
        -
        PHP 문서는 HTML 문서 내에 삽입되거나 별도의 문서로 구성되어 서버 내 일반적으로 모듈 형태로 탑재된 PHP 인터프리터에 의해 실행된다. </p>
    <p class="auto-style6">
        - 실행된 결과 값은 웹 서버 소프트웨어를 거쳐 클라이언트에 전달된다.
    </p>
    <p class="auto-style6">
        -
        PHP는 Perl, C 언어 등을 기반으로 하며, 대체적으로 Apache 모듈과 함께 사용되고, 데이터베이스 저장을 위해서는 통상적으로 MySQL과 함께 사용된다.</p>
    <h1>
        간결한 문법</h1>
    <div class="line number1 index0 alt2" style="margin: 0px !important; padding: 0.5em 0.5em 0.5em 1em !important; border-width: 0px 1px 0px 0px !important; border-top-style: initial !important; border-right-style: solid !important; border-bottom-style: initial !important; border-left-style: initial !important; border-top-color: initial !important; border-right-color: rgb(229, 236, 239) !important; border-bottom-color: initial !important; border-left-color: initial !important; border-image: initial !important; outline: 0px !important; font-size: 13.2px; vertical-align: baseline !important; border-radius: 0px !important; background: none rgb(244, 250, 252) !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; white-space: pre !important; color: rgb(102, 102, 102); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: black !important;">&lt;html&gt;</code></div>
    <div class="line number2 index1 alt1" style="margin: 0px !important; padding: 0.5em 0.5em 0.5em 1em !important; border-width: 0px 1px 0px 0px !important; border-top-style: initial !important; border-right-style: solid !important; border-bottom-style: initial !important; border-left-style: initial !important; border-top-color: initial !important; border-right-color: rgb(229, 236, 239) !important; border-bottom-color: initial !important; border-left-color: initial !important; border-image: initial !important; outline: 0px !important; font-size: 13.2px; vertical-align: baseline !important; border-radius: 0px !important; background: none white !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; white-space: pre !important; color: rgb(102, 102, 102); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: black !important;">&lt;body&gt;</code></div>
    <div class="line number3 index2 alt2" style="margin: 0px !important; padding: 0.5em 0.5em 0.5em 1em !important; border-width: 0px 1px 0px 0px !important; border-top-style: initial !important; border-right-style: solid !important; border-bottom-style: initial !important; border-left-style: initial !important; border-top-color: initial !important; border-right-color: rgb(229, 236, 239) !important; border-bottom-color: initial !important; border-left-color: initial !important; border-image: initial !important; outline: 0px !important; font-size: 13.2px; vertical-align: baseline !important; border-radius: 0px !important; background: none rgb(244, 250, 252) !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; white-space: pre !important; color: rgb(102, 102, 102); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: rgb(255, 20, 147) !important;">echo</code>
        <code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: blue !important;">&quot;Hello world&quot;</code><code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: black !important;">;</code></div>
    <div class="line number4 index3 alt1" style="margin: 0px !important; padding: 0.5em 0.5em 0.5em 1em !important; border-width: 0px 1px 0px 0px !important; border-top-style: initial !important; border-right-style: solid !important; border-bottom-style: initial !important; border-left-style: initial !important; border-top-color: initial !important; border-right-color: rgb(229, 236, 239) !important; border-bottom-color: initial !important; border-left-color: initial !important; border-image: initial !important; outline: 0px !important; font-size: 13.2px; vertical-align: baseline !important; border-radius: 0px !important; background: none white !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; white-space: pre !important; color: rgb(102, 102, 102); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: black !important;">&lt;?php</code></div>
    <div class="line number5 index4 alt2" style="margin: 0px !important; padding: 0.5em 0.5em 0.5em 1em !important; border-width: 0px 1px 0px 0px !important; border-top-style: initial !important; border-right-style: solid !important; border-bottom-style: initial !important; border-left-style: initial !important; border-top-color: initial !important; border-right-color: rgb(229, 236, 239) !important; border-bottom-color: initial !important; border-left-color: initial !important; border-image: initial !important; outline: 0px !important; font-size: 13.2px; vertical-align: baseline !important; border-radius: 0px !important; background: none rgb(244, 250, 252) !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; white-space: pre !important; color: rgb(102, 102, 102); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: rgb(255, 20, 147) !important;">echo</code>
        <code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: blue !important;">&quot;Hello world&quot;</code><code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: black !important;">;</code></div>
    <div class="line number6 index5 alt1" style="margin: 0px !important; padding: 0.5em 0.5em 0.5em 1em !important; border-width: 0px 1px 0px 0px !important; border-top-style: initial !important; border-right-style: solid !important; border-bottom-style: initial !important; border-left-style: initial !important; border-top-color: initial !important; border-right-color: rgb(229, 236, 239) !important; border-bottom-color: initial !important; border-left-color: initial !important; border-image: initial !important; outline: 0px !important; font-size: 13.2px; vertical-align: baseline !important; border-radius: 0px !important; background: none white !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; white-space: pre !important; color: rgb(102, 102, 102); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: black !important;">?&gt;</code></div>
    <div class="line number7 index6 alt2" style="margin: 0px !important; padding: 0.5em 0.5em 0.5em 1em !important; border-width: 0px 1px 0px 0px !important; border-top-style: initial !important; border-right-style: solid !important; border-bottom-style: initial !important; border-left-style: initial !important; border-top-color: initial !important; border-right-color: rgb(229, 236, 239) !important; border-bottom-color: initial !important; border-left-color: initial !important; border-image: initial !important; outline: 0px !important; font-size: 13.2px; vertical-align: baseline !important; border-radius: 0px !important; background: none rgb(244, 250, 252) !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; white-space: pre !important; color: rgb(102, 102, 102); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: black !important;">&lt;/body&gt;</code></div>
    <div class="line number8 index7 alt1" style="margin: 0px !important; padding: 0.5em 0.5em 0.5em 1em !important; border-width: 0px 1px 0px 0px !important; border-top-style: initial !important; border-right-style: solid !important; border-bottom-style: initial !important; border-left-style: initial !important; border-top-color: initial !important; border-right-color: rgb(229, 236, 239) !important; border-bottom-color: initial !important; border-left-color: initial !important; border-image: initial !important; outline: 0px !important; font-size: 13.2px; vertical-align: baseline !important; border-radius: 0px !important; background: none white !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: 400; font-style: normal; min-height: auto !important; white-space: pre !important; color: rgb(102, 102, 102); font-variant-ligatures: normal; font-variant-caps: normal; letter-spacing: normal; orphans: 2; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; text-decoration-style: initial; text-decoration-color: initial;">
        <code class="auto-style6" style="border-style: none !important; border-color: inherit !important; border-width: 0px !important; margin: 0px !important; padding: 0px !important; outline: 0px; vertical-align: baseline !important; border-radius: 0px !important; background: none !important; bottom: auto !important; float: none !important; height: auto !important; left: auto !important; line-height: 1.1em !important; overflow: visible !important; position: static !important; right: auto !important; text-align: left !important; top: auto !important; width: auto !important; box-sizing: content-box !important; font-family: Courier, monospace; font-weight: normal !important; font-style: normal !important; min-height: auto !important; color: black !important;">&lt;/html&gt;</code></div>
    <p>
        &nbsp;</p>
    <p class="auto-style51">
        출처 : 한국정보통신기술협회</p>
<p class="auto-style21">
        <strong>
        <asp:Button ID="Button1" runat="server" BackColor="Purple" CssClass="auto-style6" ForeColor="White" Height="87px" OnClick="Button1_Click" Text="Back" Width="196px" />
        </strong></p>
</asp:Content>

